In [1]:
import numpy as np

In [2]:
!ls

data  preprocessdata.py  qm7.mat  qm7-mlp.ipynb  savedata.py  Untitled.ipynb


In [3]:
X = np.load('data/coulomb_matrix.npy')

In [12]:
def randomize_coulomb_matrix(m):
    """
    Randomize a Coulomb matrix as decribed in Montavon et al., _New Journal
    of Physics_ __15__ (2013) 095003:
        1. Compute row norms for M in a vector row_norms.
        2. Sample a zero-mean unit-variance noise vector e with dimension
           equal to row_norms.
        3. Permute the rows and columns of M with the permutation that
           sorts row_norms + e.
    Parameters
    ----------
    m : ndarray
        Coulomb matrix.
    n_samples : int, optional (default 1)
        Number of random matrices to generate.
    seed : int, optional
        Random seed.
    """
    rval = []
    row_norms = np.asarray([np.linalg.norm(row) for row in m], dtype=float)
#     rng = np.random.RandomState(234)
    for i in range(1):
#         e = rng.normal(size=row_norms.size)
        p = np.argsort(row_norms)
        
        new = m[p][:, p]  # permute rows first, then columns
        rval.append(new)
    return rval

In [13]:
randomize_coulomb_matrix(X)

IndexError: too many indices for array

In [19]:
triuind = (np.arange(23)[:,np.newaxis] <= np.arange(23)[np.newaxis,:]).flatten()

In [17]:
def realize(X):
		def _realize_(x):
			inds = np.argsort(-np.linalg.norm(x, axis=0))
			x = x[inds,:][:,inds]
			x = x.flatten()[triuind]
			return x
		return np.array([_realize_(z) for z in X])
    
def normalize(X): return X/X.max()

In [14]:
def realize(X):
		def _realize_(x):
			inds = np.argsort(-(x**2).sum(axis=0)**.5)
			x = x[inds,:][:,inds]*1
# 			x = x.flatten()[triuind]
			return x
		return np.array([_realize_(z) for z in X])
    

In [20]:
X = realize(X)

In [60]:
from sklearn import preprocessing
X_scaled = preprocessing.StandardScaler().fit_transform(X)

In [63]:
X_scaled.mean()

-2.6197517e-06

In [64]:
X_scaled.std()

0.9999977

In [32]:
X_scaled

array([[-0.6379835 , -1.6926005 , -1.7807381 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.16074952, -1.781634  , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 ,  0.10190791, -2.0048385 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       ...,
       [-0.38568667, -0.7976758 ,  0.81254226, ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.17017595, -0.9636898 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.15610896, -0.2319861 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ]], dtype=float32)

In [33]:
X_scaled_max = preprocessing.MinMaxScaler().fit_transform(X)

In [37]:
X_scaled_max.min()

0.0

In [ ]:
arr = np.arange(1, 10).reshape(3, 3); arr
inds = np.argsort(-(arr**2).sum(axis=0)**.5+np.random.normal(0,1,arr[0].shape)); inds
arr[inds, :]
arr = arr[inds, :][:, inds]; arr
triuind = (np.arange(3)[:,np.newaxis] <= np.arange(3)[np.newaxis,:]).flatten(); triuind
arr.flatten()[triuind]

In [56]:
arr = np.arange(1, 10).reshape(3, 3); arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
-np.linalg.norm(arr, axis=1)

array([ -3.74165739,  -8.77496439, -13.92838828])

In [58]:
inds = np.argsort(-np.linalg.norm(arr, axis=1)); inds

array([2, 1, 0])

In [44]:
arr[inds]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [48]:
arr = arr[inds][:, inds]; arr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
triuind = (np.arange(3)[:,np.newaxis] <= np.arange(3)[np.newaxis,:]); triuind

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [49]:
arr.flatten()

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [50]:
arr.flatten()[triuind]

array([9, 8, 7, 5, 4, 1])

In [66]:
import joblib

In [67]:
some_model = joblib.load('models/regression.pkl')  
some_model

ModuleNotFoundError: No module named 'sklearn.linear_model._coordinate_descent'