In [1]:
import numpy as np

In [18]:
X = np.load('../data/coulomb_matrix.npy')

In [53]:
class Input():

	def __init__(self,X):
		self.step  = 1.0
		self.noise = 1.0
		self.triuind = (numpy.arange(23)[:,numpy.newaxis] <= numpy.arange(23)[numpy.newaxis,:]).flatten()
		self.max = 0
		for _ in range(10): self.max = numpy.maximum(self.max,self.realize(X).max(axis=0))
		X = self.expand(self.realize(X))
		self.nbout = X.shape[1]
		self.mean = X.mean(axis=0)
		self.std = (X - self.mean).std()
	
	def realize(self,X):
		def _realize_(x):
			inds = numpy.argsort(-(x**2).sum(axis=0)**.5+numpy.random.normal(0,self.noise,x[0].shape))
			x = x[inds,:][:,inds]*1
			x = x.flatten()[self.triuind]
			return x
		return numpy.array([_realize_(z) for z in X])

	def expand(self,X):
		Xexp = []
		for i in range(X.shape[1]):
			for k in numpy.arange(0,self.max[i]+self.step,self.step):
				Xexp += [numpy.tanh((X[:,i]-k)/self.step)]
		return numpy.array(Xexp).T
	
	def normalize(self,X): return (X-self.mean)/self.std
	
	def forward(self,X): return self.normalize(self.expand(self.realize(X))).astype('float32')

NameError: name 'Module' is not defined

In [43]:
def expand(X):
		Xexp = []
		for i in range(X.shape[1]):
			for k in np.arange(0, max_el1[i]+ 1, 1):
				Xexp += [np.tanh((X[:, i]-k)/1)]
		return np.array(Xexp).T

In [52]:
expand(X).shape

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
triuind = (np.arange(23)[:, np.newaxis] <= np.arange(23)[np.newaxis, :]).flatten()

In [30]:
for _ in range(10): self.max = numpy.maximum(self.max,self.realize(X).max(axis=0))

In [42]:
max_el1 = []
for _ in range(10):
    max_el = np.maximum(0, randomized_coulomb_matrix(X).max(axis=0))
    max_el1.append(max_el)
max_el1)   

[array([3.8802344e+02, 4.7143398e+01, 4.7179157e+01, 4.7015327e+01,
       2.9816092e+01, 2.9696894e+01, 2.8664648e+01, 4.3631244e+00,
       4.3776526e+00, 4.3798757e+00, 4.3672738e+00, 4.3683023e+00,
       4.3599339e+00, 4.3591256e+00, 4.3552999e+00, 4.3566885e+00,
       4.3530092e+00, 3.6440275e+00, 3.6388965e+00, 3.6355908e+00,
       2.9248354e+00, 2.8945923e+00, 2.8974977e+00, 7.3516693e+01,
       2.1396669e+01, 2.1029133e+01, 2.1074989e+01, 2.1020258e+01,
       2.0714666e+01, 4.3660054e+00, 4.3603921e+00, 4.3675995e+00,
       4.3670931e+00, 4.3631372e+00, 4.3586655e+00, 4.3514237e+00,
       4.3518209e+00, 3.6672108e+00, 3.6691842e+00, 3.6386392e+00,
       3.6389039e+00, 3.6362875e+00, 2.9244583e+00, 2.9001348e+00,
       2.9055276e+00, 7.3516693e+01, 1.9309612e+01, 1.9309538e+01,
       1.9309513e+01, 1.9158461e+01, 3.6728642e+00, 3.6834919e+00,
       3.6764684e+00, 3.6773779e+00, 3.6769085e+00, 3.6743150e+00,
       3.6740081e+00, 3.6766357e+00, 3.6385384e+00, 3.6435654

In [51]:
??np.arange

In [50]:
23*23

529

In [37]:
def randomized_coulomb_matrix(X, noise=1, seed=234):
    def _realize_(x):
        rs = np.random.RandomState(seed=seed)
        gaussian_error = rs.normal(0, noise, x[0].shape)
        inds = np.argsort(-np.linalg.norm(x, axis=0) + gaussian_error)  # sort indices of coulomb matrix
        x = x[inds][:, inds]  # permute rows first, then columns
        x = x.flatten()[triuind]  # flatten and slice
        return x

    return np.array([_realize_(z) for z in X])

In [38]:
randomized_coulomb_matrix(X)

array([[36.858105 ,  2.9076326,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [36.858105 , 12.599944 ,  1.4731002, ...,  0.       ,  0.       ,
         0.       ],
       [36.858105 , 14.261827 ,  2.9247003, ...,  0.       ,  0.       ,
         0.       ],
       ...,
       [53.358707 , 19.153597 ,  8.569991 , ...,  0.       ,  0.       ,
         0.       ],
       [36.858105 , 12.490625 , 12.540301 , ...,  0.       ,  0.       ,
         0.       ],
       [36.858105 , 12.602233 ,  7.2795167, ...,  0.       ,  0.       ,
         0.       ]], dtype=float32)

In [17]:
#https://github.com/cc-ats/Neural_Network/blob/training/NN_Input_Handler.py

In [10]:
thetaMatrix = np.full([23, 23], 1)

In [15]:
x = []
    #change range to get more/less inputs
    #-5 to 0 chosen because outside of this range each dimension of the matrix
    #remains relatively constant
for i in range(-5, 0):
    x.append(np.tanh(np.divide(np.add(X, i * thetaMatrix), thetaMatrix)))
    #convert x into a numpy array for calculations
npx = np.array(x)
npx.shape

(5, 7165, 23, 23)

In [14]:
T = 0
bcB = npx >= T
bcB.shape

(18951425,)

In [16]:
npx

array([[[[ 1.        , -0.97000424, -0.97000545, ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [-0.97000424, -0.99975321, -0.99983565, ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [-0.97000545, -0.99983565, -0.99975321, ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         ...,
         [-0.9999092 , -0.9999092 , -0.9999092 , ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [-0.9999092 , -0.9999092 , -0.9999092 , ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [-0.9999092 , -0.9999092 , -0.9999092 , ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ]],

        [[ 1.        ,  0.9999995 , -0.97033528, ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [ 0.9999995 ,  1.        , -0.9982732 , ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         [-0.97033528, -0.9982732 , -0.99975321, ..., -0.9999092 ,
          -0.9999092 , -0.9999092 ],
         ...,
         [-0.9999092 , -0.9999092 

In [3]:
!ls

kernel-ridge-2020-06-18-gaussian.ipynb	 qm7-mlp.ipynb
kernel-ridge-2020-06-18-Laplacian.ipynb  svr-2020-06-20.ipynb
linear-regression-2020-06-19.ipynb	 Untitled.ipynb


In [7]:
X = np.load('../data/coulomb_matrix.npy')

In [20]:
def randomized_coulomb_matrix(X, noise=1, seed=234):
    def _realize_(x):
        rs = np.random.RandomState(seed=seed)
        gaussian_error = rs.normal(0, noise, x[0].shape)
        inds = np.argsort(-np.linalg.norm(x, axis=1) + gaussian_error)  # sort indices of coulomb matrix
        x = x[inds][:, inds]  # permute rows first, then columns
        x = x.flatten()[triuind]  # flatten and slice
        return x

    return np.array([_realize_(z) for z in X])


def expand(X, step=1):
    Xexp = []
    for i in range(X.shape[1]):
        for k in np.arange(0, np.max(i) + step, step):
            Xexp += [np.tanh((X[:, i] - k) / step)]
    return np.array(Xexp).T

In [8]:
triuind = (np.arange(23)[:, np.newaxis] <= np.arange(23)[np.newaxis, :]).flatten()

In [22]:
X_exapnded = expand(randomized_coulomb_matrix(X))

In [23]:
X_exapnded.shape

(7165, 38226)

In [12]:
def randomize_coulomb_matrix(m):
    """
    Randomize a Coulomb matrix as decribed in Montavon et al., _New Journal
    of Physics_ __15__ (2013) 095003:
        1. Compute row norms for M in a vector row_norms.
        2. Sample a zero-mean unit-variance noise vector e with dimension
           equal to row_norms.
        3. Permute the rows and columns of M with the permutation that
           sorts row_norms + e.
    Parameters
    ----------
    m : ndarray
        Coulomb matrix.
    n_samples : int, optional (default 1)
        Number of random matrices to generate.
    seed : int, optional
        Random seed.
    """
    rval = []
    row_norms = np.asarray([np.linalg.norm(row) for row in m], dtype=float)
#     rng = np.random.RandomState(234)
    for i in range(1):
#         e = rng.normal(size=row_norms.size)
        p = np.argsort(row_norms)
        
        new = m[p][:, p]  # permute rows first, then columns
        rval.append(new)
    return rval

In [13]:
randomize_coulomb_matrix(X)

IndexError: too many indices for array

In [19]:
triuind = (np.arange(23)[:,np.newaxis] <= np.arange(23)[np.newaxis,:]).flatten()

In [17]:
def realize(X):
		def _realize_(x):
			inds = np.argsort(-np.linalg.norm(x, axis=0))
			x = x[inds,:][:,inds]
			x = x.flatten()[triuind]
			return x
		return np.array([_realize_(z) for z in X])
    
def normalize(X): return X/X.max()

In [14]:
def realize(X):
		def _realize_(x):
			inds = np.argsort(-(x**2).sum(axis=0)**.5)
			x = x[inds,:][:,inds]*1
# 			x = x.flatten()[triuind]
			return x
		return np.array([_realize_(z) for z in X])
    

In [20]:
X = realize(X)

In [60]:
from sklearn import preprocessing
X_scaled = preprocessing.StandardScaler().fit_transform(X)

In [63]:
X_scaled.mean()

-2.6197517e-06

In [64]:
X_scaled.std()

0.9999977

In [32]:
X_scaled

array([[-0.6379835 , -1.6926005 , -1.7807381 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.16074952, -1.781634  , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 ,  0.10190791, -2.0048385 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       ...,
       [-0.38568667, -0.7976758 ,  0.81254226, ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.17017595, -0.9636898 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ],
       [-0.6379835 , -0.15610896, -0.2319861 , ..., -0.0821199 ,
        -0.02956635, -0.0354635 ]], dtype=float32)

In [33]:
X_scaled_max = preprocessing.MinMaxScaler().fit_transform(X)

In [37]:
X_scaled_max.min()

0.0

In [ ]:
arr = np.arange(1, 10).reshape(3, 3); arr
inds = np.argsort(-(arr**2).sum(axis=0)**.5+np.random.normal(0,1,arr[0].shape)); inds
arr[inds, :]
arr = arr[inds, :][:, inds]; arr
triuind = (np.arange(3)[:,np.newaxis] <= np.arange(3)[np.newaxis,:]).flatten(); triuind
arr.flatten()[triuind]

In [56]:
arr = np.arange(1, 10).reshape(3, 3); arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
-np.linalg.norm(arr, axis=1)

array([ -3.74165739,  -8.77496439, -13.92838828])

In [58]:
inds = np.argsort(-np.linalg.norm(arr, axis=1)); inds

array([2, 1, 0])

In [44]:
arr[inds]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [48]:
arr = arr[inds][:, inds]; arr

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
triuind = (np.arange(3)[:,np.newaxis] <= np.arange(3)[np.newaxis,:]); triuind

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [49]:
arr.flatten()

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [50]:
arr.flatten()[triuind]

array([9, 8, 7, 5, 4, 1])

In [66]:
import joblib

In [67]:
some_model = joblib.load('models/regression.pkl')  
some_model

ModuleNotFoundError: No module named 'sklearn.linear_model._coordinate_descent'